#! /bin/bash

source ~/.bashrc

py36

appen_to_python_path_if_not $PWD
appen_to_path_if_not $PWD/bin

repositories --upload
repositories --make-map
repositories --star

git commit -m 'update' -a
git push
