#! /bin/bash

source ~/.bashrc

# py37 ???
source /opt/python-virtual-env/py38/bin/activate

append_to_python_path_if_not $PWD
append_to_path_if_not $PWD/bin

repositories --upload
repositories --make-map
repositories --star

git commit -m 'update' -a
git push
